# Default values for energy-monitor.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: adamwalford/energy-monitor
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

service:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "2112"
  type: ClusterIP
  port: 80

envVars:
  - name: OCTOPUS_ENERGY_API_KEY
    valueFrom:
      secretKeyRef: 
        name: octopus-energy
        key: API_KEY
  - name: METER_MPAN
    valueFrom:
      secretKeyRef: 
        name: octopus-energy
        key: MPAN
  - name: METER_SERIAL_NUMBER
    valueFrom:
      secretKeyRef: 
        name: octopus-energy
        key: SERIAL_NUMBER
  - name: OCTOPUS_PRODUCT
    valueFrom:
      secretKeyRef: 
        name: octopus-energy
        key: PRODUCT
  - name: OCTOPUS_TARIFF
    valueFrom:
      secretKeyRef: 
        name: octopus-energy
        key: TARIFF

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
