replicaCount: 1

image:
  repository: adamwalford/office-lights
  pullPolicy: IfNotPresent
  tag: 0.2.0

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

hueBridge:
  secretName: hue

mqtt:
  secretName: mqtt
